services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=fixerio_db
    volumes:
      - postgres_vol:/var/lib/postgresql/data:rw  
    ports:
      - "5431:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - pgadmin_vol:/var/lib/pgadmin
    ports:
      - "8080:80"
volumes:
  pgadmin_vol:
  postgres_vol: